spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

spring.profiles.active: prod

logging.level.root: info
logging.level.org.springframework.security: debug


# jwt
jwt:
  header: Access-Token
  secret: liaodw
  expiration: 100000
  tokenHead: Bearer
  white: /user/login